### ISSUE TITLE
keep stats for game restart 

### ISSUE THREAD

**Issue by timschoch** [ltsSmitty/consistent-guest-stats#1]
First off, your plugin saved our huge family park. It was exactly what I was looking for at the perfect time. Thanks 🙏

I noticed that the values get reset and deactivated when I close the game. Instead it would be desirable that once the plugin is activated, it keeps running and I don't have to set the values ever time the game loads.

Tim

**Comment by ltsSmitty** [comment]
Hey Tim, thanks for submitting the issue. This has been addressed in #[9e6f419](https://github.com/ltsSmitty/consistent-guest-stats/commit/9e6f41906e3c949ad8f9905bcabdb20fdce353de) and you can [download the new version](https://github.com/ltsSmitty/consistent-guest-stats/releases/tag/v1.1.0) to replace your existing one. Cheers!

**Comment by timschoch** [comment]
It works like a charm. Thanks for fixing this <3
